### ISSUE TITLE
[功能请求] 增加GM命令的Log打印延迟时间

### ISSUE THREAD

**Issue by linchengzzz** [LviatYi/MetaWorldNPT#1]
**来源**

- [ ] GToolkit `gtoolkit`
- [ ] Log4Ts `mw-log4ts`
- [x] GodMod `mw-god-mod`
- [ ] LynxUi `mw-lynx-ui`

**描述需求**
在option配置里面可自定义 GM 命令的输出打印时间

**额外信息**
![image](https://github.com/user-attachments/assets/63e55927-b431-477b-a565-6c29edc07ae8)

```typescript
 /**
     * God Mod 命令参数选项.
     */
    export interface GodCommandParamOption<P = string> {
        /**
         * 󰌆数据验证器组合.
         */
        validator?: (DataValidator<P> | DataValidatorWithReason<P>)[];
        label?: string;
    }
```

**Comment by LviatYi** [comment]
We add this feature in GodMod 36.1.3.

Thanks for your advice!
